collections: 
    weblog:
        output: true
    recipes:
         output: true
    movies:
         output: true
    books:
         output: true
         
google_analytics: UA-216187335-1

markdown: kramdown
kramdown:
    auto_ids: true
