collections: 
    weblog:
        output: true
    recipes:
         output: true
    movies:
         output: true
    books:
         output: true
         
google_analytics: G-1J8DRB0K1K

markdown: kramdown
kramdown:
    auto_ids: true
